### ISSUE TITLE
Feature request: show multiple gpu at the same time

### ISSUE THREAD

**Issue by ubless607** [Maimonator/vscode-gpu-monitor#1]
Feature request: show multiple gpu at the same time

**Comment by apex-tal** [comment]
how would you imagine this feature working?

**Comment by Maimonator** [comment]
I fear that the status bar is too small for multiple GPUs, do you have a suggestion as to how that will work?

**Comment by ubless607** [comment]
@Maimonator I am sorry. I don't have any idea by now.

**Comment by Maimonator** [comment]
Well if you have a suggestion let me know
