### ISSUE TITLE
Annoying startup failure

### ISSUE THREAD

**Issue by Erik262** [Maimonator/vscode-gpu-monitor#3]
![image](https://github.com/user-attachments/assets/d9a4a24d-c955-41f7-91da-2051b2bcf972)
I'm running a macOS computer and I get this annoying message every time. Is there a way to get rid of it at startup?

**Comment by Erik262** [comment]
@Maimonator Are there any settings I can use to silence the very annoying notifications that keep coming up every time I open a new window????????

**Comment by Maimonator** [comment]
This only works if have the `nvidia-smi` binary.
If you have it but it's not in your path you can set a new path for the binary in the settings.
If you don't have a an Nvidia GPU you can disable the extension.
https://code.visualstudio.com/docs/editor/extension-marketplace#_disable-an-extension

**Comment by Erik262** [comment]
@Maimonator I understand that this does not work on Apple computers, but I do work remotely on instances that have Nvidia GPUs, which I connect to using VSCode. However, every time I start up VSCode or open a new window, a popup appearse connected to a GPU and with Nvidia's `nvidia-smi`, everything else works flawlessly.

**Comment by Maimonator** [comment]
@Erik262 you can disable the VSCode extension for your local workspace and enable it remotely
From VSCode docs - 
"You can disable an extension globally or just for your current Workspace"
